### ISSUE TITLE
-e option is failing

### ISSUE THREAD

**Issue by hsolbrig** [hsolbrig/pyjsg#14]
Traceback (most recent call last):
  File "generate_parser", line 9, in <module>
    generate(sys.argv[1:])
  File "lib/python3.8/site-packages/pyjsg/parser_impl/generate_python.py", line 131, in generate
    evaluate("generate_python_namespace", opts.outfile, opts.verbose)               # Don't pollute namespace
  File "lib/python3.8/site-packages/pyjsg/parser_impl/generate_python.py", line 120, in evaluate
    mod = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 553, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'

**Comment by hsolbrig** [comment]
This has been fixed by changing generate_parser to go directly to the code
