### ISSUE TITLE
Pipfile should pin antlr4-python3-runtime to 4.9

### ISSUE THREAD

**Issue by cmungall** [hsolbrig/pyjsg#20]
Tests fail with 4.10:

```bash
➜  pyjsg git:(main) pipenv run python -m unittest  tests/test_issues/test_multi_type_omissions.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/cjm/repos/pyjsg/tests/test_issues/test_multi_type_omissions.py", line 3, in <module>
    from tests.utils.harness import Harness
  File "/Users/cjm/repos/pyjsg/tests/utils/harness.py", line 7, in <module>
    from pyjsg.parser_impl.generate_python import parse
  File "/Users/cjm/repos/pyjsg/pyjsg/parser_impl/generate_python.py", line 11, in <module>
    from pyjsg.parser.jsgParser import jsgParser
  File "/Users/cjm/repos/pyjsg/pyjsg/parser/jsgParser.py", line 164, in <module>
    class jsgParser ( Parser ):
  File "/Users/cjm/repos/pyjsg/pyjsg/parser/jsgParser.py", line 168, in jsgParser
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/Users/cjm/.local/share/virtualenvs/pyjsg-H6gwH1qg/lib/python3.9/site-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/Users/cjm/.local/share/virtualenvs/pyjsg-H6gwH1qg/lib/python3.9/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
```

currently the pipfile has antlr4-python3-runtime = "~=4.9"

this actually allows 4.10 to be installed (the syntax always throws me - see https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean)

We need to pin to 4.9

I can't seem to find the release notes for antlr4-python3-runtime 4.10 so I don't know what change caused this

**Comment by cmungall** [comment]
Here is a description of 4.10: https://github.com/antlr/antlr4/releases

They say "This is a very major release with a number of important changes" so not really following semver? It implies we should pin more aggressively
